### PR TITLE
Website Cards v2

### PR DESCRIPTION
**Pull request by Matteas-Eden**
# Overview

As a follow-up to [this lovely PR](https://github.com/JM-Atkinson/576i.nz-hugo/pull/3), I've refactored the website cards to be more responsive and automatically populate their images via [Icon Horse](https://icon.horse) (which takes the images directly from the site's favicon).

This all works great, and even has nice fallbacks for those pesky websites which don't supply a favicon. However, some websites which provide favicons don't provide *high-quality* favicons, so the resulting card ends up looking bad. Not sure how to fix this, other than bugging the site owner.

# Preview
image

### CODE REVIEW

**Comment by JM-Atkinson** [comment]
These look great. But I think they are too big. If they could be shrunk to maybe 50% of their current size, that would be good.

**Comment by Matteas-Eden** [comment]
Here's a resized version, what do you think?

Also keen for any thoughts on what the description for each site should be. Ideally it would be grabbed from the metadata on the website itself, but I've already learned my lesson around making assumptions about the quality of these websites.

image

**Comment by JM-Atkinson** [comment]
This is better, but still too big I think. Can it be shrunk say 20% in on
either side?

**Comment by Matteas-Eden** [comment]
**Desktop view**
image

**Mobile view**
image

**Comment by Matteas-Eden** [comment]
# Updated design

**Desktop**
image
**Mobile**
image

**Pull request merged**
